[package]
name = "day2"
version = "0.1.0"
authors = ["Robin Verlangen <robin+github@us2.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
